name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci
      
      - name: Build
        run: npm run build
        env:
          NODE_ENV: production

      # Adiciona arquivo .nojekyll para evitar processamento Jekyll
      - name: Add .nojekyll file
        run: touch ./dist/.nojekyll
      
      # Verifica se existe um arquivo 404.html, senão cria um
      - name: Create 404 page if not exists
        run: |
          if [ ! -f ./dist/404.html ]; then
            cp ./dist/index.html ./dist/404.html
          fi

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true # Garante que a branch gh-pages seja limpa e recriada
          keep_files: false # Não mantém arquivos antigos
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
